export const news = [
  {
    slug: 'breaking-news',
    title: 'BREAKING NEWS',
    imgUrl: '/assets/images/hero/phone.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 6,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'leading and control',
    title: 'Leading and Control in Health Services Management',
    imgUrl: '/assets/images/courses/anaestheticist.jpg',
    date: '21 January 2021',
    author: 'admin',
    commentsCount: 4,
    category: 'economical',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Health and the Environment',
    imgUrl: '/assets/images/courses/biotechologist.jpg',
    date: '26 December 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'health and sanitisation',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Contextualisation of Health Sciences Education',
    imgUrl: '/assets/images/courses/geriontology.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 1,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Eskom did this and that. No electricity for everybody',
    imgUrl: '/assets/images/courses/physiotherapist.jpg',
    date: '01 september 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'finance',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },{
    slug: 'breaking-news',
    title: 'BREAKING NEWS',
    imgUrl: '/assets/images/hero/phone.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 6,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'leading and control',
    title: 'Leading and Control in Health Services Management',
    imgUrl: '/assets/images/courses/anaestheticist.jpg',
    date: '21 January 2021',
    author: 'admin',
    commentsCount: 4,
    category: 'economical',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Health and the Environment',
    imgUrl: '/assets/images/courses/biotechologist.jpg',
    date: '26 December 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'health and sanitisation',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Contextualisation of Health Sciences Education',
    imgUrl: '/assets/images/courses/geriontology.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 1,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Eskom did this and that. No electricity for everybody',
    imgUrl: '/assets/images/courses/physiotherapist.jpg',
    date: '01 september 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'finance',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },{
    slug: 'breaking-news',
    title: 'BREAKING NEWS',
    imgUrl: '/assets/images/hero/phone.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 6,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'leading and control',
    title: 'Leading and Control in Health Services Management',
    imgUrl: '/assets/images/courses/anaestheticist.jpg',
    date: '21 January 2021',
    author: 'admin',
    commentsCount: 4,
    category: 'economical',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Health and the Environment',
    imgUrl: '/assets/images/courses/biotechologist.jpg',
    date: '26 December 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'health and sanitisation',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Contextualisation of Health Sciences Education',
    imgUrl: '/assets/images/courses/geriontology.jpg',
    date: '26 March 2023',
    author: 'admin',
    commentsCount: 1,
    category: 'business',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
  {
    slug: 'breaking-news',
    title: 'Eskom did this and that. No electricity for everybody',
    imgUrl: '/assets/images/courses/physiotherapist.jpg',
    date: '01 september 2020',
    author: 'admin',
    commentsCount: 0,
    category: 'finance',
    content: 'Another learner, who chose to remain anonymous, said that when she registered at the college she was told that she will get a stipend which is at least R 7000.',
  },
];
