export const students = [
  {
    _id: 'jdjdjfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'kenny',
    lastname: 'masinga',
    imgUrl: '/assets/portal/images/user6.png',
    year: 'Third year Student',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    course: {
      courseName: 'Information Engineering',
    },
  },
  {
    _id: 'jdjdjhgfdsdfu434567hfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Nancy',
    lastname: 'Davolio',
    imgUrl: '/assets/portal/images/user5.png',
    year: 'Third year Student',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    course: {
      courseName: 'Chartered Accountant',
    },
  },
  {
    _id: 'jdjutrdhtrdfghf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Nasimiyu',
    lastname: 'Ndhlovu',
    imgUrl: '/assets/portal/images/user4.png',
    year: 'Third year Student',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    course: {
      courseName: 'Nursing',
    },
  },
  {
    _id: 'jdjidfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Iulia',
    lastname: 'Ibu',
    imgUrl: '/assets/portal/images/user3.png',
    year: 'Third year Student',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    course: {
      courseName: 'Archeology',
    },
  },
  {
    _id: 'jdjdjdjdderrjfbshfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Tim',
    lastname: 'Zonke',
    imgUrl: '/assets/portal/images/user2.png',
    year: 'Third year Student',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    course: {
      courseName: 'Actuarial Science',
    },
  },
  {
    _id: 'jdjgfdsxcvgrhfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Marble',
    lastname: 'Phiri',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    imgUrl: '/assets/portal/images/user1.png',
    year: 'Third year Student',
    course: {
      courseName: 'Chemical Engineering',
    },
  },
  {
    _id: 'jdytredgtrdfghrjfbshfhf',
    studentID: 'E43 4542 412 834D',
    firstname: 'Sizwe',
    lastname: 'Khumalo',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    imgUrl: '/assets/portal/images/user3.png',
    year: 'Third year Student',
    course: {
      courseName: 'Industrial Engineering',
    },
  },
];
