export const events = [
  {
      _id: 'event 1',
      title: 'Community Service',
      date: '05 December 2001',
      startTime: '09:00AM',
      endTime: '10:00AM',
      content: 'Cleaning Kutlwanong Hall in Soweto',
      location: 'Zola, Soweto',
  },
  {
      _id: 'event 2',
      title: 'Covid Conference',
      date: '12 December 2010',
      startTime: '08:00AM',
      endTime: '04:00PM',
      content: 'Last conference of the year blah blah blah blah',
      location: 'Johanneburg Hall',
  },
  {
      _id: 'event 3',
      title: 'Food for work Service',
      date: '05 December 2001',
      startTime: '12:00AM',
      endTime: '01:00PM',
      content: 'Students will be working for food and so on and so for',
      location: 'Durban',
  },
  {
      _id: 'event 4',
      title: '32km Marathon',
      date: '30 January 2023',
      startTime: '09:00AM',
      endTime: '10:00PM',
      content: 'we will be running from johannesburg to pretorial to donate to charity',
      location: 'Zola, Soweto',
  },
  {
      _id: 'event 5',
      title: 'Buy groceries',
      date: '12 February 2023',
      startTime: '08:00AM',
      endTime: '08:30PM',
      content: 'We will be buying groceries for the homeless in Yeoville',
      location: 'Yeoville, Johanneburg',
  },
  {
      _id: 'event 6',
      title: 'Gym',
      date: '05 June 2001',
      startTime: '04:00PM',
      endTime: '06:00PM',
      content: 'Will be gyming at virgin active gym please bring long towels and tracksuits.',
      location: 'Durban',
  },
]
