export const lecturers = [
  {
    _id: 'jdjdjfhf',
    firstname: 'kenny',
    lastname: 'masinga',
    imgUrl: '/assets/portal/images/user1.png',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    worksAs: 'Lecturer',
    workDuration: '3 months',
  },
  {
    _id: 'jdjdjhgfdsdfu434567hfhf',
    firstname: 'Nancy',
    lastname: 'Davolio',
    imgUrl: '/assets/portal/images/user2.png',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    worksAs: 'Lecturer',
    workDuration: '10 years',
  },
  {
    _id: 'jdjutrdhtrdfghf',
    firstname: 'Nasimiyu',
    lastname: 'Ndhlovu',
    imgUrl: '/assets/portal/images/user3.png',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    worksAs: 'Lecturer',
    workDuration: '1 week',
  },
  {
    _id: 'jdjidfhf',
    firstname: 'Iulia',
    lastname: 'Ibu',
    imgUrl: '/assets/portal/images/user4.png',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    worksAs: 'Lecturer',
    workDuration: '4 years',
  },
  {
    _id: 'jdjdjdjdderrjfbshfhf',
    firstname: 'Tim',
    lastname: 'Zonke',
    imgUrl: '/assets/portal/images/user5.png',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    worksAs: 'Lecturer',
    workDuration: '12 years',
  },
  {
    _id: 'jdjgfdsxcvgrhfhf',
    firstname: 'Marble',
    lastname: 'Phiri',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    imgUrl: '/assets/portal/images/user6.png',
    worksAs: 'Lecturer',
    workDuration: '2 years',
  },
  {
    _id: 'jdytredgtrdfghrjfbshfhf',
    firstname: 'Sizwe',
    lastname: 'Khumalo',
    email: 'kennymasinga@star.com',
    phoneNumber: '+27 42 365 77779',
    imgUrl: '/assets/portal/images/user3.png',
    worksAs: 'Lecturer',
    workDuration: '9 months',
  },
];